### GET request to example server
GET https://estoquespring-production-f826.up.railway.app//itens/listagem
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInN1YiI6Im1hdXJpY2lvQGdtYWlsLmNvbSIsImV4cCI6MTc3NjkxMjcxNCwiaWF0IjoxNzc2OTA0MDc0fQ.ZH9vAeQPeQvDvQBl32_cs8GuZrkSGq07XlcrOJI2xUk
###

POST https://estoquespring-production-f826.up.railway.app/auth/register
Content-Type: application/json

{
  "name": "Mauricio",
  "email": "mauricio@gmail.com",
  "password": "bombom"
}
###

POST https://estoquespring-production-f826.up.railway.app/auth/login
Content-Type: application/json

{
"email": "mauricio@gmail.com",
"password": "bombom"
}