### GET request to example server
GET localhost:8080/itens/listagem
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInN1YiI6Im1hdXJpY2lvQGdtYWlsLmNvbSIsImV4cCI6MTc3NzA3ODA4MSwiaWF0IjoxNzc3MDY5NDQxfQ.EIOyRngJMRjzqMc4548mAokgOIVlRwIrDzl-am2ocko
###

POST localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Mauricio",
  "email": "mauricio@gmail.com",
  "password": "bombom"
}
###

POST localhost:8080/auth/login
Content-Type: application/json

{
"email": "mauricio@gmail.com",
"password": "bombom"
}